name: Sync fork with upstream

on:
  schedule:
    - cron: '0 6 * * *'  # roda todo dia às 6h UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar branch main do fork
        uses: actions/checkout@v4
        with:
          ref: main  # garante que baixa a main do seu fork

      - name: Configurar git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Adicionar repositório upstream
        run: |
          git remote add upstream https://github.com/bikeanjo/institucional.git
          git fetch upstream

      - name: Reset hard da main para o upstream
        run: |
          git checkout main
          git reset --hard upstream/main

      - name: Push forçado da main para seu fork
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true